language: python

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.5.1

    - os: linux
      dist: xenial
      language: python
      python: 3.7

    - os: linux
      dist: xenial
      language: python
      python: 3.6

    - os: linux
      dist: xenial
      language: python
      python: 3.5

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
- pytest -v tests/
