language: python

matrix:
  include:
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.5.6
    
    - os: osx
      language: generic
      env: PYTHON_VERSION=3.6.8
    
    - os: windows
      language: sh
      env:
        - PATH=/c/Python36:/c/Python36/Scripts:$PATH
        - PYTHON_VERSION=3.6.8
    
    - os: windows
      language: sh
      env:
        - PATH=/c/Python37:/c/Python37/Scripts:$PATH
        - PYTHON_VERSION=3.7.3

    - os: linux
      dist: xenial
      language: python
      python: 3.7

    - os: linux
      dist: xenial
      language: python
      python: 3.6
    
    - os: linux
      dist: xenial
      language: python
      python: 3.5

    - os: linux
      dist: trusty
      language: python
      python: 3.6
    
    - os: linux
      dist: trusty
      language: python
      python: 3.5

before_install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip install -U pip;
      pip install --egg --no-binary pyenv pyenv;
      export PATH=~/.pyenv/bin:$PATH;
      eval "$(pyenv init -)";
      pyenv install --skip-existing $PYTHON_VERSION;
      pyenv global $PYTHON_VERSION;
      pyenv shell $PYTHON_VERSION;
      pip install -U pip setuptools wheel py;
    fi
    if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
      choco install python --version $PYTHON_VERSION
      python -m pip install --upgrade pip
    fi
  
# command to install dependencies
install:
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      pip3 install pytest
      pip3 install .
    else
      pip install pytest
      pip install .
    fi

# command to run tests
script:
- pytest -v tests/
